apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ephemeral-runnerdeploy
spec:
  replicas: 0  # 0 initial; ephemeral runners scale up automatically
  template:
    spec:
      repository: johanny/GitHubActionsCookbook2
      ephemeral: true   # make runner ephemeral
      labels:
        - ephemeral