name: "📝 Repository Request"
description: "Request a new repository."
title: "📝 Repository Request: "
labels:
  - "repo-request"
  - "issue-ops"
assignees:
  - "johanny-M"
projects: "johanny-M/4"

body:
  - type: input
    id: name
    attributes:
      label: GITHUBACTIONCOOKBOOK2
      description: "Enter the repository name in lower-case and kebab-case."
      placeholder: cookbook2
    validations:
      required: true

  - type: dropdown
    id: department
    attributes:
      label: Department
      description: "Pick your department. It will be used as a prefix for the repository name."
      options:
        - dep1
        - dep2
      default: dep1
    validations:
      required: true